name: Build and Publish to Test PyPI (Linux only)

on:
  push:
    tags:
      - "dev-v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine

      - name: "Check current directory"
        run: |
          pwd
          ls
          ls -R

      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: |
            echo "Downloading Zig for Linux x86_64..."
            curl -L https://ziglang.org/builds/zig-linux-x86_64-0.12.0.tar.xz | tar -xJ
            echo "Adding Zig to PATH..."
            export PATH=$PWD/zig-linux-x86_64-0.12.0:$PATH

            echo "Zig version:"
            zig version

            echo "Building Zig library..."
            cd zig
            zig build

            echo "Copying built libs to slowda package..."
            cp zig-out/lib/* ../slowda/

            echo "Done with Zig build and copy."
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload to Test PyPI
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
