name: Build and Publish to Test PyPI (Linux only)

on:
  push:
    tags:
      - "dev-v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: "1"

      - name: Upload to Test PyPI
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
