name: Build Linux Wheel (Debug)

on:
  push:
    branches:
      - gemini-way # Or any branch you use for development
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  build_wheels:
    name: Build wheel on Linux
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Be specific for debugging

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0 # Use your project's Zig version

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheel
        run: cibuildwheel --output-dir wheelhouse

      - name: Store wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheel
          path: ./wheelhouse

  publish_wheels:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
